name: s3-dvc.yml
on: [push]

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install CML Utility
        uses: iterative/setup-cml@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure DVC remote for AWS S3 Bucket
        run: |
          dvc remote modify --local s3remote access_key_id ${{ secrets.ACCESS_KEY_ID }}
          dvc remote modify --local s3remote secret_access_key ${{ secrets.SECRET_ACCESS_KEY }}
          dvc remote modify --local s3remote region ${{ secrets.REGION }}

#          Analytic Utility
          dvc remote list
          dvc config --local

      - name: Pull Data & Models from DVC Remote ( S3 Bucket )
        run: dvc pull -v

      - name: Train / Evaluate Model
        run: python script.py

      - name: Track new Artifacts with DVC
        run: | 
          dvc add data/ models/
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add data.dvc models.dvc
          git commit -m "Update DVC artifacts [Skip CI]" || "echo No changes to commit"

      - name: Push DVC Artifacts to S3 Bucket
        run: dvc push -v

      - name: Publish CML Report
        run: |
          echo "# Model Report" > report.md
          echo "## Metrics" >> report.md
          awk ’NR%4{print " " $0}{print ""}’ metrics.txt >> report.md
          echo "## Confusion Matrix" >> report.md
          echo "![](./ conf_matrix . png ) " >> report . md
          cml comment create report.md